### ISSUE TITLE
Bad anser "1"

### ISSUE THREAD

**Issue by joaquinperaza** [muhilham/google-currency#1]
Hi @muhilham, what could be causing to get returned "1"?
I was using this options, and testing manual the error occurs randomly 7 from 10 times more or less.
```
var converter = require("google-currency")
 const options = {
        from: "BTC",
        to: "UYU",
        amount: 1
    };
    converter(options).then(value => {console.log(value)})
```
Response: 
`Object {amount: 1, converted: 1, from: "AED", to: "AED", url: undefined}`

**Comment by joaquinperaza** [comment]
I am working on the fix, is because google guys want to look better and use this domain: https://finance.google.com/finance/converter and the redirect discard the query the parameters

**Comment by joaquinperaza** [comment]
Waintg merging with fixed fork

**Comment by muhilham** [comment]
hi @joaquinperaza sorry i didnt notice. Have found the problem ?

**Comment by joaquinperaza** [comment]
Yes, it was solved with the pull request you accepted, thanks!

**Comment by muhilham** [comment]
aaah, didnt see the timeline, i thought it was after the PR merged
